import Head from "next/head";
import { useLayoutEffect, useRef } from "react";
import Header from "../components/Header";
import MainContent from "../components/MainContent";
import Sidebar from "../components/Sidebar";
import useElementOffsetContext from "../context/ElementOffsetContext";

export default function Home() {
  const mainRef = useRef<HTMLDivElement>(null)
  const { setMainContainer } = useElementOffsetContext();

  useLayoutEffect(() => {
    mainRef.current && setMainContainer({ main: mainRef.current })
  }, [])

  return (
    <>
      <Head>
        <title>Zin Kyaw Moe | Profile and Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main ref={mainRef} className="body">
        <Header />
        <div className="test">
          <Sidebar />
          <MainContent />
        </div>
      </main>
    </>
  );
}
